name: Deploy

on:
  release:
    types: [published]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build:prod

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: publish to NPM
        working-directory: dist
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: archive files
        run: tar -czvf discord-express.tar.gz dist && zip -rv discord-express.zip dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./discord-express.tar.gz
            ./discord-express.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: generate docs
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: run Typedoc
        run: pnpm generateDocs

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs
