name: Node.js CI

on:
  push: {}
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: test on node ${{ matrix.node }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node: [12.x, 14.x, 17.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint

      - name: test
        run: pnpm test
